project:
  type: website
  output-dir: _site
  resources:
    - CNAME
    - .nojekyll
    - profile.jpeg
    - profile_2.jpg
    - profile_3.jpg
    - cv.pdf
    - cv_fr.pdf
    - orcid_logo_icon_145004.png
    - lang-switcher.js
    - favicon.ico
    - favicon.svg
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon-192x192.png
    - favicon-512x512.png
    - apple-touch-icon.png
    - favicon-meta.html
    - site.webmanifest
    - pml_remote_slides.html
  render:
    - "*.qmd"
    # - "!teaching.qmd"
    # - "!teaching_fr.qmd"

website:
  title: "Gabrielle Péloquin-Skulski"
  site-url: "https://gskulski.com"
  favicon: favicon.ico
  google-analytics: "G-7XZWY833KE"

  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd

  page-footer:
    left: |
      © 2026 Gabrielle Péloquin-Skulski
    right: |
      Built with [Quarto](https://quarto.org)

format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: false
    include-in-header:
      - favicon-meta.html
    include-after-body:
      - text: |
          <script src="lang-switcher.js"></script>
